name: CI conda

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
    

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -el {0}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: "actions/checkout@v6"
        with:
          fetch-depth: 0

      # Setup conda env
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: metacoag
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false

      - name: "Setup metacoag on ${{ matrix.os }} for Python ${{ matrix.python-version }}"
        run: |
          python --version
          python -m pip install --upgrade pip
          pip install --upgrade pip wheel setuptools "flit>=3.8,<4" "flit_core>=3.2,<4"
          flit install
      
      - name: "Generate coverage report on ${{ matrix.os }} for Python ${{ matrix.python-version }}"
        run: |
          pip install pytest pytest-cov
          pytest --cov=metacoag --cov-report=xml --cov-append
